### ISSUE TITLE
Premature resolving of UrlGenerator breaks other extensions that register routes

### ISSUE THREAD

**Issue by clarkwinkelmann** [NikoVonLas/flarum-ext-web-push#1]
Hello,

Following the issue reported here https://discuss.flarum.org/d/7026-linguist-customize-translations-with-ease/57 I investigated why your extension might break compatibility with Linguist.

I noticed that you resolve the `UrlGenerator` in the constructor of an event listener here https://github.com/NikoVonLas/flarum-ext-web-push/blob/e13f0d7127e983b73e086e883362cc148f2a1e76/src/Listener/SendWebPushNotification.php#L24

Because event listeners are instantiated right when they are registered, anything resolved in its constructor will be immediately resolved early in the forum lifecycle.

This means that the `UrlGenerator` is resolved at the time time your `extend.php` is read, which in turn resolves the route collection, which in turn prevents any extension that's read after yours to register new routes.

You should instead resolve the UrlGenerator, and possibly all other classes used in the constructor directly in the `sendWebPushNotification` method using `$url = app(UrlGenerator::class)`.

This will also improve performance because those will be resolved only when your event triggers, instead of every time Flarum code runs.

**Comment by NikoVonLas** [comment]
Thanks you for this fix!
